name: Integration Tests

on:
  pull_request:
    paths:
      - '**.psd1'
      - '!**/classes.psd1'

jobs:
  integration-tests:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Module
        run: make build
