name: Integration Tests

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!**/.gitkeep'
      - '!LICENSE'
      - '!Makefile'
      - '!.github/workflows/release.yml'
      - '!docs/**'
  workflow_dispatch:

permissions:
  actions: read
  packages: read
  contents: read

jobs:
  integration-tests:
    runs-on: windows-latest
    
    env:
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Profile
        shell: pwsh
        run: .\.build\scripts\Setup-RunnerProfile.ps1 -Verbose

      - name: Setup Container (Custom)
        shell: pwsh
        run: .\.build\custom\Setup-Container.ps1
      
      - name: Build Module
        run: .\.build\scripts\Build-PSModule.ps1
      
      - name: Pester Tests
        shell: pwsh
        run: .\.build\scripts\Invoke-PSModulePester.ps1 -Verbose:$false

      - name: Check Package Version
        shell: pwsh
        run: .\.build\scripts\Test-GitHubPackageVersion.ps1
