name: Release Module

on:
  push:
    branches:
      - main
    paths:
      - '**.psd1'
      - '!**/classes.psd1'

permissions:
  actions: write
  packages: write
  contents: write

jobs:
  release-module:
    runs-on: windows-latest
    
    env:
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Profile
        shell: pwsh
        run: .\.build\scripts\Setup-RunnerProfile.ps1 -Verbose

      - name: Setup Container (Custom)
        shell: pwsh
        run: .\.build\custom\Setup-Container.ps1
      
      - name: Build Module
        shell: pwsh
        run: .\.build\scripts\Build-PSModule.ps1
      
      - name: Pester Tests
        shell: pwsh
        run: .\.build\scripts\Invoke-PSModulePester.ps1 -Verbose:$false
      
      - name: Publish Module
        shell: pwsh
        run: .\.build\scripts\Publish-GitHubModule.ps1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.module_name }}-${{ env.module_version }}
          name: ${{ env.module_name }}-${{ env.module_version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          prerelease: false
          draft: false
          body: |
            ### Create a token with `read:packages` scope
            1. Generate a [new personal access token](https://github.com/settings/tokens/new)
            2. Select `read:packages` scope, specify a name and expiration, then click 'Generate token'
            3. Save a copy of the token securely

            ### Prerequisites
            If you are using PowerShell 7 or later, `Microsoft.PowerShell.PSResourceGet` is included.
            Please use the below command if you are using an earlier version of PowerShell -
            ```powershell
            Install-Module -Name 'Microsoft.PowerShell.PSResourceGet'
            ```

            ### From GitHub Packages
            ```powershell
            # Register GitHub Packages source (one-time setup)
            Register-PSResourceRepository -Name 'GitHub' -Uri 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'

            # Prepare token
            $githubUsername = 'GITHUB_USERNAME'
            $githubToken = 'GITHUB_TOKEN'

            $githubCredential = [pscredential]::new(
                $githubUsername,
                (ConvertTo-SecureString $githubToken -AsPlainText -Force)
            )
            
            # Install the module
            Install-PSResource -Name '${{ env.module_name }}' -Repository GitHub -Version ${{ env.module_version }} -Credential $githubCredential
            ```

            # Hashes (Sha256)
            * ${{ env.nupkg_name }} - ${{ env.nupkg_hash }}
            ---
            *This release was automatically generated by GitHub Actions*
