name: Release Module

on:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  packages: write
  contents: write

jobs:
  release-module:
    runs-on: windows-latest
    
    env:
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Profile
        shell: pwsh
        run: .\.build\scripts\Setup-RunnerProfile.ps1 -Verbose
      
      - name: Build Module
        run: .\.build\scripts\Build-PSModule.ps1
      
      - name: Pester Tests
        shell: pwsh
        run: .\.build\scripts\Invoke-PSModulePester.ps1 -Verbose:$false

      - name: Check Manifest Version
        shell: pwsh
        run: .\.build\scripts\Test-GitHubPackageVersion.ps1
      
      - name: Publish Module
        shell: pwsh
        run: .\.build\scripts\Publish-GitHubModule.ps1
