name: Update Documentation

on:
  pull_request:
    paths:
      - '**.psd1'
      - '!**/classes.psd1'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    runs-on: windows-latest
    
    env:
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup Profile
        shell: pwsh
        run: .\.build\scripts\Setup-RunnerProfile.ps1 -Verbose
      
      - name: Build Module
        shell: pwsh
        run: .\.build\scripts\Build-PSModule.ps1
      
      - name: Generate Documentation
        shell: pwsh
        run: .\.build\scripts\Write-PSModuleDocs.ps1

      - name: Commit Documentation Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "DocsBot"
          git add docs/
          git diff --staged --quiet || git commit -m "AUTO: Exported Command Documentation"
          git push origin ${{ github.head_ref }}
